from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from services.quiz_generator import generate_quiz
from services.insight_generator import generate_insights
from utils.cache import DataCache

router  = APIRouter()
_cache: DataCache = None

# Empty leaderboard — fills dynamically as users play
_leaderboard = []

def set_cache(cache: DataCache):
    global _cache
    _cache = cache


class QuizRequest(BaseModel):
    country_a:    str
    country_b:    str
    shock_type:   str   = "war"
    intensity:    float = 0.7
    cascade:      dict  = {}
    country_b_si: dict  = {}


class InsightRequest(BaseModel):
    country_a:    str
    country_b:    str
    shock_type:   str   = "war"
    intensity:    float = 0.7
    cascade:      dict  = {}
    country_b_si: dict  = {}
    clusters:     list  = []


class LeaderboardUpdate(BaseModel):
    name: str
    xp:   int


@router.post("/generate")
async def generate_quiz_endpoint(req: QuizRequest):
    """
    Generates quiz questions from simulation result.
    Called after user runs a simulation.
    Questions are dynamically generated by Mistral
    based on actual cascade results.
    """
    questions = await generate_quiz(
        simulation_result = req.dict(),
        num_questions     = 5
    )
    return {
        "status":    "success",
        "count":     len(questions),
        "questions": questions
    }


@router.post("/insights")
async def generate_insights_endpoint(req: InsightRequest):
    """
    Generates AI insight cards from simulation result.
    Content is dynamically generated by Mistral
    based on actual SI scores and cascade data.
    """
    insights = await generate_insights(
        simulation_result = req.dict()
    )
    return {
        "status":   "success",
        "count":    len(insights),
        "insights": insights
    }


@router.get("/leaderboard")
def get_leaderboard():
    """
    Returns current leaderboard.
    Starts empty, fills as users submit scores.
    Sorted by XP descending.
    """
    ranked = sorted(
        _leaderboard,
        key     = lambda x: x["xp"],
        reverse = True
    )
    for i, entry in enumerate(ranked):
        entry["rank"] = i + 1

    return {
        "count":       len(ranked),
        "leaderboard": ranked
    }


@router.post("/leaderboard/update")
def update_leaderboard(data: LeaderboardUpdate):
    """
    Updates user XP on leaderboard.
    If user exists — updates XP if new score higher.
    If user does not exist — adds new entry.
    """
    global _leaderboard

    # Check if user already exists
    for entry in _leaderboard:
        if entry["name"].lower() == data.name.lower():
            # Only update if new XP is higher
            if data.xp > entry["xp"]:
                entry["xp"] = data.xp
            return {
                "status":      "updated",
                "name":        data.name,
                "xp":          entry["xp"],
                "leaderboard": get_leaderboard()["leaderboard"]
            }

    # New user — add to leaderboard
    _leaderboard.append({
        "name": data.name,
        "xp":   data.xp,
        "rank": 0
    })

    return {
        "status":      "added",
        "name":        data.name,
        "xp":          data.xp,
        "leaderboard": get_leaderboard()["leaderboard"]
    }


@router.delete("/leaderboard/reset")
def reset_leaderboard():
    """
    Resets leaderboard — for testing only.
    """
    global _leaderboard
    _leaderboard = []
    return {"status": "reset", "leaderboard": []}